services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "5173:5173"
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./src:/var/www
      - ./../front/dist:/srv/frontend:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      php:
        condition: service_started
      db:
        condition: service_started
    networks:
      back_default:
        aliases:
          - caddy

  php:
    build: ./php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      db:
        condition: service_started
    networks:
      back_default:
        aliases:
          - php

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scoundrel
      MYSQL_USER: master
      MYSQL_PASSWORD: ofpuppets
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - back_default

networks:
  back_default:
    name: back_default
    driver: bridge

volumes:
  db_data:
  caddy_data:
  caddy_config:
